name: MaSuiteTeleports
main: fi.matiaspaavilainen.masuiteteleports.bukkit.MaSuiteTeleports
version: ${project.version}
author: Masagameplay
depends: [MaSuiteCore]
commands:
  spawn:
    permission: masuiteteleports.spawn.teleport
    description: Teleports to spawn
  setspawn:
    permission: masuiteteleports.spawn.set
    aliases: [spawnset, createspawn]
    description: Sets spawn point of the server
  delspawn:
    permission: masuiteteleports.spawn.delete
    aliases: [spawndel, deletespawn]
    description: Deletes spawn point of the server
  tp:
    aliases: [teleport]
    description: Teleports to given target
  tptoggle:
    permission: masuiteleports.teleport.toggle
    aliases: [teleporttoggle]
    description: Enable or disable force teleportations
  tphere:
    permission: masuiteteleports.teleport.force.here
    aliases: [teleporthere]
    description: Teleports target to sender
  tpall:
    permission: masuiteteleports.teleport.force.all
    aliases: [teleportall]
    description: Teleports all of the players to sender
  tpaccept:
    permission: masuiteteleports.teleport.accept
    aliases: [tpyes, teleportaccept]
    description: Accepts teleportation request
  tpdeny:
    permission: masuiteteleports.teleport.deny
    aliases: [tpno, teleportdeny]
    description: Denies teleportation request
  tpa:
    permission: masuiteteleports.teleport.request
    description: Sends teleportationg request to target
  tpahere:
    permission: masuiteteleports.teleport.here
    description: Sends teleportation request to target
  tpalock:
    permission: masuiteteleports.teleport.lock
    description: Locks request to accepting or denying them
  back:
    permission: masuiteteleports.back
    description: Teleports to your last known location